sudo: required
services:
  - docker
before_install:
  # Use the encryption file that has the credentials to Google Cloud Service Account
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Install Google Cloud CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install Kubectl
  - gcloud components update kubectl
  # Authenticate on Google Cloud
  - gcloud auth activate-service-account --key-file service-account.json
  